services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   container_name: form-builder-backend
  #   volumes:
  #     - .:/usr/src/app # Sync code changes for hot reload
  #     - node_modules/usr/src/app/node_modules # Ensure node_modules is persisted within the container
  #   ports:
  #     - "3000:3000" # Map the application port to the host
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  #   restart: always

  db:
    image: postgres:15
    container_name: postgres-db-1
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=form_builder
    restart: always

volumes:
  db_data:
# docker run -p 5432:5432 \
# -e POSTGRES_PASSWORD=admin \
# -e POSTGRES_USER=admin \
# -e POSTGRES_DB=form_builder \
# postgres:15
