version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: form-builder-production
    command: >
      sh -c "bun prisma migrate deploy &&
             bun run server:dev"
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: postgres-db
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
    restart: always

volumes:
  db_data:
